#!/bin/sh

set -e

lb config noauto \
    --apt-http-proxy "${http_proxy}" \
    --apt-indices false \
    --apt-recommends false \
    --archive-areas "main contrib non-free" \
    --bootappend-live "boot=live live-config.noautologin quiet noroot toram" \
    --clean \
    --distribution testing \
    --iso-application "PolyProg Live" \
    --iso-publisher "PolyProg" \
    --iso-volume "PolyProg Live" \
    --memtest none \
    --firmware-chroot true \
    --mirror-bootstrap http://mirror.switch.ch/ftp/mirror/debian/ \
    --mirror-chroot-security http://security.debian.org/ \
    --mirror-binary http://mirror.switch.ch/ftp/mirror/debian/ \
    --mirror-binary-security http://security.debian.org/ \
    "${@}"
