#!/usr/bin/python3
# -*- coding: utf-8 -*-

import argparse


__author__ = "Benjamin Schubert <ben.c.schubert@gmail.com>"


def parse_args():
    parser = argparse.ArgumentParser(description="Replaces password entry in a file")
    parser.add_argument("-p", "--password", required=True, help="new password to use")
    parser.add_argument("-f", "--file", required=True, help="File in which to make the replacement")

    return vars(parser.parse_args())


def main(file, password):
    with open(file, "r") as f:
        data = f.readlines()

    with open(file, "w") as f:
        for line in data:
            if "password" in line:
                line = line.split("=")[0] + '= "' + password + '",'
            f.write(line)

if __name__ == "__main__":
    main(**parse_args())
