#!/bin/sh

set -eux

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi


readonly BASE_KS='polyprog-client.ks'
readonly NAME='PolyProg-live'
readonly FEDORA_VERSION='24'

readonly FLAT_KS="flat-${BASE_KS}"

# TODO maybe can remove virt-install libvirt-daemon-config-network
dnf --assumeyes install \
	lorax virt-install libvirt-daemon-config-network pykickstart anaconda

setenforce 0

ksflatten --config "${BASE_KS}" --output "${FLAT_KS}" \
	  --version "F${FEDORA_VERSION}"
livemedia-creator --ks "${FLAT_KS}" \
		  --project "${NAME}" --volid "${NAME}" \
		  --iso-name "${NAME}.iso" --title "${NAME}" \
		  --releasever "${FEDORA_VERSION}" \
		  --make-iso --iso-only --macboot \
 		  --no-virt  # TODO why needed? seems related to iso creation

setenforce 1
