#!/bin/sh

set -eu

PREFIX='plg-'

hostname=$(hostname)
ip=''

ifconfig | awk '/inet / {print $2}' | while read addr
do
	[ "${addr}" = '127.0.0.1' ] && continue
	[ "${hostname}" = "${PREFIX}${addr}" ] && exit 0
	ip="${addr}"
done

hostnamectl --set-hostname "${PREFIX}${addr}"
systemctl restart systemd-networkd
systemctl restart avahi-daemon
