# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1456779371);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1456779011);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 0);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1456779251);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1456779131);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 225280);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160214092551");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage", "http://ec2.hc2.ch/");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":3}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1456865290775");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1456778952951");
user_pref("datareporting.policy.firstRunTime", "1456778890774");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1241);
user_pref("datareporting.sessions.current.main", 50);
user_pref("datareporting.sessions.current.sessionRestored", 1162);
user_pref("datareporting.sessions.current.startTime", "1456780224836");
user_pref("datareporting.sessions.current.totalTime", 13);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1456778888742,\"a\":13,\"t\":572,\"c\":true,\"m\":623,\"fp\":4513,\"sr\":4140}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1456779463421,\"a\":23,\"t\":113,\"c\":true,\"m\":41,\"fp\":1327,\"sr\":1166}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1456779579030,\"a\":1,\"t\":7,\"c\":true,\"m\":40,\"fp\":893,\"sr\":914}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1456780131540,\"a\":3,\"t\":77,\"c\":true,\"m\":61,\"fp\":1328,\"sr\":1217}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1456767295000,\"mt\":1455444673000}}}");
user_pref("gecko.buildID", "20160214092551");
user_pref("gecko.mstone", "44.0.2");
user_pref("idle.lastDailyNotification", 1456779287);
user_pref("media.gmp-manager.buildID", "20160214092551");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1456779287);
user_pref("places.history.expiration.transient_current_max_pages", 12838);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.browser.homepage.disable_button.bookmark_page", false);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1456779287);
user_pref("toolkit.startup.last_success", 1456780224);
user_pref("toolkit.telemetry.cachedClientID", "29701e24-168d-44d0-ab9e-f4ba1b86df67");
user_pref("toolkit.telemetry.previousBuildID", "20160214092551");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
