# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("browser.download.dir", "/home/polyprog/Desktop");
user_pref("browser.download.manager.closeWhenDone", true);
user_pref("browser.startup.homepage", "https://ec2.hc2.ch");
user_pref("privacy.donottrackheader.enabled", true);
