# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.download.dir", "/home/polyprog/Desktop");
user_pref("browser.download.manager.closeWhenDone", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage", "http://www.spoj.com/PP2013WC/");
user_pref("privacy.donottrackheader.enabled", true);
