#!/bin/sh

### BEGIN INIT INFO
# Provides:          polyprog-firewall
# Required-Start:    $network $named
# Required-Stop:     $network $named
# Default-Start:     S
# Default-Stop:      
# Short-Description: Starts the PolyProg Firewall
# Description:       Starts the PolyProg Firewall. This ensures that
#                    contestants cannot access unauthorized websites.
### END INIT INFO

set -e
. /lib/lsb/init-functions

N=/etc/init.d/polyprog-firewall

setup_firewall() {
  # Flush all rules
  /sbin/iptables --flush
  /sbin/iptables --delete-chain

  # A chain to log and then reject packets
  /sbin/iptables --new-chain logreject
  /sbin/iptables --append logreject --jump LOG --log-prefix "polyprog-firewall: " --match limit --limit 20/minute
  /sbin/iptables --append logreject --jump REJECT

  # General policies: drop everything
  /sbin/iptables --policy INPUT DROP
  /sbin/iptables --policy FORWARD DROP
  /sbin/iptables --policy OUTPUT DROP

  # Accept related packets
  /sbin/iptables --append INPUT --match state --state ESTABLISHED,RELATED --jump ACCEPT 
  /sbin/iptables --append OUTPUT --match state --state ESTABLISHED,RELATED --jump ACCEPT 

  # Allow loopback
  /sbin/iptables --append INPUT --source 127.0.0.1/8 --destination 127.0.0.1/8 --jump ACCEPT 
  /sbin/iptables --append OUTPUT --source 127.0.0.1/8 --destination 127.0.0.1/8 --jump ACCEPT 

  # Allow DNS
  /sbin/iptables --append OUTPUT --protocol udp --dport domain --jump ACCEPT

  # Allow incoming ssh connections
  /sbin/iptables --append INPUT --protocol tcp --dport ssh --jump ACCEPT

  # Allow PING (outgoing replies are RELATED, hence accepted, too)
  /sbin/iptables --append INPUT --protocol icmp --icmp-type echo-request --jump ACCEPT

  # Allow HTTP to selected hosts
  # hc2.ch, doc.hc2.ch
  /sbin/iptables --append OUTPUT --protocol tcp --destination 62.75.159.9 --dport http --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination 62.75.159.9 --dport https --jump ACCEPT
  # polyprog.epfl.ch
  /sbin/iptables --append OUTPUT --protocol tcp --destination 128.178.50.212 --dport http --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination 128.178.50.212 --dport https --jump ACCEPT
  # yandex.com and related (using dns names here as I'm unsure whether those IPs stay constant)
  /sbin/iptables --append OUTPUT --protocol tcp --destination yandex.com --dport http --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination yandex.com --dport https --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination www.yandex.com --dport http --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination www.yandex.com --dport https --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination yandex.st --dport http --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination yandex.st --dport https --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination passport.yandex.com --dport http --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination passport.yandex.com --dport https --jump ACCEPT
  # Contest servers
  /sbin/iptables --append OUTPUT --protocol tcp --destination contest.yandex.com --dport http --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination contest.yandex.com --dport https --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination contest2.yandex.com --dport http --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination contest2.yandex.com --dport https --jump ACCEPT
  # Some web resources that are often used
  /sbin/iptables --append OUTPUT --protocol tcp --destination ajax.googleapis.com --dport http --jump ACCEPT
  /sbin/iptables --append OUTPUT --protocol tcp --destination ajax.googleapis.com --dport https --jump ACCEPT

  # All other outgoing packets are logged and rejected
  /sbin/iptables --append OUTPUT --jump logreject
}

stop_firewall() {
  # Flush all rules
  /sbin/iptables --flush
  /sbin/iptables --delete-chain

  # General policies: accept input and output
  /sbin/iptables --policy INPUT ACCEPT
  /sbin/iptables --policy FORWARD DROP
  /sbin/iptables --policy OUTPUT ACCEPT
}

case "$1" in
  start)
	log_action_begin_msg "Setting up PolyProg Firewall"
        setup_firewall
        log_action_end_msg $?
	;;
  stop)
	log_action_begin_msg "Stopping PolyProg Firewall"
        stop_firewall
        log_action_end_msg $?
	;;
  reload|restart|force-reload)
        ;;
  *)
	echo "Usage: $N start|stop" >&2
	exit 1
	;;
esac

exit 0
