#!/bin/bash

### BEGIN INIT INFO
# Provides:          polyprog-network
# Required-Start:    $network $named
# Required-Stop:     $network $named
# Default-Start:     S
# Default-Stop:      
# Short-Description: Connects to the network using 802.1x authentication
# Description:       Connects to the network. Authenticates using 802.1x.
### END INIT INFO

. /lib/lsb/init-functions

N=/etc/init.d/polyprog-network

wait_for_connectivity() {
    log_action_begin_msg "Waiting for network connectivity"
    local n_tries=0
    while ! host polyprog.epfl.ch >/dev/null 2>&1 && [ "$n_tries" -lt 2 ]; do
        n_tries=$((n_tries + 1))
        log_action_cont_msg " waiting ($n_tries / 3)"
        sleep 2
    done

    [ "$n_tries" -lt 2 ]
    local has_connectivity=$?
    log_action_end_msg $has_connectivity
    return $has_connectivity
}

start_network() {
    if ! wait_for_connectivity; then
        dhclient -r eth0
        killall wpa_supplicant

        wpa_supplicant -D wext -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf -B
        sleep 8
        dhclient wlan0
    else
        return 0
    fi
}

stop_network() {
    dhclient -r eth0
    killall wpa_supplicant
}

case "$1" in
  start)
        log_action_begin_msg "Connecting to the network"
        start_network
        log_action_end_msg $?
        ;;
  stop)
        log_action_begin_msg "Disconnecting from the network"
        stop_network
        log_action_end_msg $?
        ;;
  reload|restart|force-reload)
        log_action_begin_msg "Re-connecting to the network"
        stop_network
        start_network
        log_action_end_msg $?
        ;;
  *)
        echo "Usage: $N start|stop" >&2
        exit 1
        ;;
esac

exit 0
