#!/bin/bash

### BEGIN INIT INFO
# Provides:          polyprog-network
# Required-Start:    $network $named
# Required-Stop:     $network $named
# Default-Start:     S
# Default-Stop:      
# Short-Description: Connects to the network using 802.1x authentication
# Description:       Connects to the network. Authenticates using 802.1x.
### END INIT INFO

. /lib/lsb/init-functions

N=/etc/init.d/polyprog-network

start_network() {
    wpa_supplicant -D wired -i eth0 -c /etc/wpa_supplicant/wpa_supplicant.conf -B
    sleep 2
    dhclient eth0
}

stop_network() {
    dhclient -r eth0
    killall wpa_supplicant
}

case "$1" in
  start)
        start_network
        local status=$?
        log_action_begin_msg "Connecting to the network"
        log_action_end_msg $status
        ;;
  stop)
        log_action_begin_msg "Disconnecting from the network"
        stop_network
        log_action_end_msg $?
        ;;
  reload|restart|force-reload)
        log_action_begin_msg "Re-connecting to the network"
        stop_network
        start_network
        log_action_end_msg $?
        ;;
  *)
        echo "Usage: $N start|stop" >&2
        exit 1
        ;;
esac

exit 0
