#!/bin/sh

# Sets some gconf settings that are specific to the polyprog live system

polyprog_gconf ()
{
	# Checking if already configured
	if [ -e /var/lib/live/config/polyprog-gconf ]
	then
		return
	fi

	echo -n " polyprog-gconf"

	configure_polyprog_gconf
}

configure_polyprog_gconf ()
{
        # Configure the browser homepage
        sudo -u "$LIVE_USERNAME" gsettings set org.gnome.Epiphany homepage-url "'http://m1.hc2.ch/'"

        # Prevent automounting of media
        sudo -u "$LIVE_USERNAME" gconftool-2 --type bool --set /apps/nautilus/preferences/media_automount false

	# Creating state file
	touch /var/lib/live/config/polyprog-gconf
}

polyprog_gconf
