# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1480085532);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migrated-sync-button", true);
user_pref("browser.migration.version", 38);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.search.countryCode", "CH");
user_pref("browser.search.hiddenOneOffs", "Yahoo,Bing,Amazon.com,DuckDuckGo,Twitter,Wikipedia (en)");
user_pref("browser.search.region", "CH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20161025170457");
user_pref("browser.slowStartup.averageTime", 2469);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage", "http://polyprog.epfl.ch/santa");
user_pref("browser.startup.homepage_override.buildID", "20161025170457");
user_pref("browser.startup.homepage_override.mstone", "49.0.2");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 3);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20161125);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1480085594326");
user_pref("datareporting.sessions.current.activeTicks", 51);
user_pref("datareporting.sessions.current.firstPaint", 1491);
user_pref("datareporting.sessions.current.main", 30);
user_pref("datareporting.sessions.current.sessionRestored", 1443);
user_pref("datareporting.sessions.current.startTime", "1480085874612");
user_pref("datareporting.sessions.current.totalTime", 357);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1480085530761,\"a\":9,\"t\":140,\"c\":true,\"m\":363,\"fp\":3710,\"sr\":3558}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.lastUpdate.buildID", "20161025170457");
user_pref("dom.apps.lastUpdate.mstone", "49.0.2");
user_pref("dom.apps.reset-permissions", true);
user_pref("e10s.rollout.cohort", "disqualified-test");
user_pref("e10s.rollout.cohortSample", "0.003588");
user_pref("experiments.activeExperiment", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 52442);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
